---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-app
  namespace: argocd
  annotations:
    weave.gitops.flamingo/base-url: "https://demo3.weavegitops.com"
    weave.gitops.flamingo/cluster-name: "default%2Fflamingo-host25-cluster-33"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./demo/artifacts/default-app
    repoURL: oci://ghcr.io/flux-subsystem-argo/flamingo/manifests
    targetRevision: v2.7
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - FluxSubsystem=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fsa-installation
  namespace: argocd
  annotations:
    weave.gitops.flamingo/base-url: "https://demo3.weavegitops.com"
    weave.gitops.flamingo/cluster-name: "default%2Fflamingo-host25-cluster-33"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./demo/artifacts/fsa-installation
    repoURL: oci://ghcr.io/flux-subsystem-argo/flamingo/manifests
    targetRevision: v2.7
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - FluxSubsystem=true
