---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fsa-installation
  namespace: argocd
  annotations:
    metadata.weave.works/flamingo-fsa-installation: "https://localhost:8080/applications/argocd/fsa-installation?view=tree"
    link.argocd.argoproj.io/external-link: "https://demo3.weavegitops.com/kustomize/details?clusterName=default%2Fflamingo-host25-cluster-33&name=fsa-installation&namespace=argocd"
spec:
  prune: true
  interval: 2m
  path: "./demo/artifacts/fsa-installation"
  sourceRef:
    kind: OCIRepository
    name: fsa-demo
    namespace: flux-system
  timeout: 10m
  targetNamespace: argocd
  wait: true
