apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.6/manifests/install.yaml
images:
  - name: quay.io/argoproj/argocd:v2.7.6
    newName: ghcr.io/flux-subsystem-argo/fsa/argocd
    newTag: v2.7.6-fl.15-main-52691a11
